name: API Test CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*

  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - qa
          - uat
        default: "qa"

  schedule:
    - cron: "0 2 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}

    steps:
      - name: Print Environment
        run: echo "Running in $ENVIRONMENT environment"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests
        run: |
          cd API_Testing_Practice
          mvn clean test -Dallure.results.directory=target/allure-results

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.38.1/allure-2.38.1.tgz
          tar -xzf allure-2.38.1.tgz
          sudo mv allure-2.38.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          cd API_Testing_Practice
          allure generate target/allure-results --clean -o target/allure-report    

      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./API_Testing_Practice/target/allure-report

      - name: List files (DEBUG)
        run: |
          ls -R

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./API_Testing_Practice/target/allure-results